global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  - job_name: "kafka_exporter"
    static_configs:
      - targets: ["kafka_exporter:9308"]
  - job_name: "zookeeper"
    static_configs:
      - targets: ["zookeeper:2181"]
  - job_name: "valkey"
    static_configs:
      - targets: ["redis_exporter:9121"]
  - job_name: "opensearch"
    static_configs:
      - targets: ["opensearch:9600"]
