global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9091"]

  - job_name: "zookeeper"
    static_configs:
      - targets: ["zookeeper:2181"]

  - job_name: "postgres"
    static_configs:
      - targets: ["db:5432"]

  - job_name: "go_services"
    static_configs:
      - targets: ["go_producer:8080", "go_sentiment_analysis:8081"]
